### ISSUE TITLE
seq2seq_model的356行，force_dec_input是不是应该等于True？

### ISSUE THREAD

**Issue by zhanghainan** [liuyuemaicha/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow#2]
感谢你代码的分享~
我在train的时候觉得，在训练的时候是不是还是应该固定decode？
还有reward的计算用乘法还是减法？我看你在另一个repository用的是乘法

**Comment by yzhihao** [comment]
@zhanghainan 请问你有语料吗？能不能分享一份呢？感谢。

**Comment by liuyuemaicha** [comment]
It should be multiply operation, now I have fixed it ,but I have not implement the project.
