### ISSUE TITLE
你好，可以发个数据集的链接吗？

### ISSUE THREAD

**Issue by yuanliping** [liuyuemaicha/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow#3]

**Comment by liuyuemaicha** [comment]
I have update the training data (examples)

**Comment by yuanliping** [comment]
thank you!

**Comment by yuanliping** [comment]
thanks for your dataset!

在2017-06-05 17:05:48，六月麦茬notifications@github.com写道：

I have update the training data (examples)
