### ISSUE TITLE
Confused by this line of code

### ISSUE THREAD

**Issue by ligua** [liuyuemaicha/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow#4]
<img width="609" alt="seq2seq_model py sublime text today at 2 31 01 pm" src="https://cloud.githubusercontent.com/assets/23098054/26829199/dcb0715e-4ac4-11e7-9a34-29209b421133.png">

**Comment by ligua** [comment]
Sorry I have no idea what this line means in type 2.......

why access the first encoder, decoder pair and then fetch the a item from it...

This is totally confusing

Or maybe I am just dumb. :)

**Comment by liuyuemaicha** [comment]
Sorry，I don't describe the type in details。in type 2，encoder_input_a is not a item,it‘s a encoder data set，so, firstly we get the encode data set encoder_input_a, and get a encode sentence by encoder_input = encoder_input_a[batch_i], we don't need to get the decoder, because the decoder is null.
